# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

stages:
  - stage: Build
    jobs:
      - deployment: DeployWeb
        displayName: deploy Web App
        dependsOn: BuildJob
        pool:
          vmImage: 'wandisco-ldma'
        environment: 'envir1'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo my first deployment
      - job: BuildJob
        steps:
          - script: echo Building!
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**/target/*.?(war|jar)'
              TargetFolder: $(Build.ArtifactStagingDirectory)

          - upload: $(Build.ArtifactStagingDirectory)

            artifact: drop
  - stage: Test
    jobs:
      - job: TestOnWindows
        steps:
          - script: echo Testing on Windows!
      - job: TestOnLinux
        steps:
          - script: echo Testing on Linux!
  - stage: Deploy
    jobs:

      - job: Deploy
        steps:
          - script: echo Deploying the code!